#!/bin/bash

xvfb-run -a coverage run --source=countess -m pytest -v -rP --doctest-modules countess/ tests/

coverage report --skip-empty --sort=-cover

#coverage html 
#python -m webbrowser -t htmlcov/index.html
