#!/bin/bash

xvfb-run coverage run --source=countess -m pytest --doctest-modules countess/ tests/

coverage report --skip-empty --sort=-cover

#coverage html 
#python -m webbrowser -t htmlcov/index.html
