#!/bin/bash
set -eu

git diff --quiet || { echo "There are unstaged changes!"; exit 1; }
git diff --cached --quiet || { echo "There are staged changes!"; exit 2; }

VERSION=$1

sed -i "s/\# CountESS .*/# CountESS $VERSION/" README.md
sed -i "s/VERSION = .*/VERSION = \"$VERSION\"/" countess/__init__.py
sed -i "s/version:.*/version: $VERSION/" docs/_config.yml

git commit -m "Bump to v$VERSION" README.md countess/__init__.py docs/_config.yml
git tag -m "CountESS version $VERSION" v$VERSION
