#!/bin/bash
set -eu

VERSION=$1

sed -i "s/\# CountESS .*/# CountESS $VERSION/" README.md
sed -i "s/VERSION = .*/VERSION = \"$VERSION\"/" countess/__init__.py
sed -i "s/title: CountESS .* Documentation/title: CountESS $VERSION Documentation/;s/\# CountESS .* Documentation/\# CountESS $VERSION Documentation/" docs/index.md

git commit -m "Bump to v$VERSION"
git tag -m "CountESS version $VERSION" v$VERSION
