name: MyPy Checks
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Checks
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install mypy~=1.0.1
    - run: mypy --strict $(git ls-files '*.py')
