name: "Nix Build"
on:
  pull_request:

jobs:
  nix_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v19
    - run: nix build
    - run: nix flake check
