name: Run Tests
on:
  pull_request:
  push:

jobs:
  run-tests-ubuntu-22_04-python-3_10:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.10
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest tests/

  run-tests-ubuntu-22_04-python-3_11_0rc2:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.11.0rc2
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.0-rc.2"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest tests/

  run-tests-ubuntu-22_04-python-3_11_0:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.11.1
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.0"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest tests/

  run-tests-ubuntu-22_04-python-3_11_1:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.11.1
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.1"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest tests/

  run-tests-ubuntu-22_04-python-3_11_2:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.11.2
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.2"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest tests/

  run-tests-ubuntu-22_04-python-3_12_0_alpha5:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.12.0alpha5
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.12.0-alpha.5"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest tests/

  run-tests-ubuntu-22_04-python-3_11_from_apt:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python from Apt
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install python3.11 python3.11-venv xvfb
    - run: python3.11 -m ensurepip
    - run: python3.11 -m pip install .[dev]
    - run: xvfb-run python3.11 -mpytest tests/

#  run-tests-ubuntu-22_04-pypy3:
#    runs-on: ubuntu-22.04
#    name: Ubuntu 22.04, PyPy 3
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v4
#      with:
#        python-version: "pypy3.9"
#    - run: sudo apt install pypy3 pypy3-tk pypy3-dev xvfb
#    - run: pypy3 -mpip install -U pip wheel
#    - run: pypy3 -mpip install .[dev]
#    - run: xvfb-run pytest tests/

  run-tests-windows-2022:
    runs-on: windows-2022
    name: Windows Server 2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/

  run-tests-macos-12:
    runs-on: macos-12
    name: macOS 12
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/
