name: Run Tests (On Push)
on:
  push:

jobs:
  run-tests-ubuntu-22_04-python-3_9:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.9
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
#    - run: xvfb-run pytest tests/

  run-tests-ubuntu-22_04-python-3_10-with-coverage:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.10 (with coverage)
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run coverage run --source countess -m pytest tests/
#    - run: coverage html
#    - uses: actions/upload-artifact@v3
#      with:
#        name: test coverage report
#        path: htmlcov/*
    - run: echo '### Coverage Report' >> $GITHUB_STEP_SUMMARY
    - run: coverage report --format=markdown >> $GITHUB_STEP_SUMMARY

#  run-tests-ubuntu-22_04-python-3_11_0rc2:
#   runs-on: ubuntu-22.04
#    name: Ubuntu 22.04, Python 3.11.0rc2
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v4
#      with:
#        python-version: "3.11.0-rc.2"
#    - run: sudo apt install xvfb
#    - run: pip install --upgrade pip
#    - run: pip install .[dev]
#    - run: xvfb-run pytest tests/
#
#  run-tests-ubuntu-22_04-python-3_11_0:
#    runs-on: ubuntu-22.04
#    name: Ubuntu 22.04, Python 3.11.1
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v4
#      with:
#        python-version: "3.11.0"
#    - run: sudo apt install xvfb
#    - run: pip install --upgrade pip
#    - run: pip install .[dev]
#    - run: xvfb-run pytest tests/
#
#  run-tests-ubuntu-22_04-python-3_11_1:
#    runs-on: ubuntu-22.04
#    name: Ubuntu 22.04, Python 3.11.1
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v4
#      with:
#        python-version: "3.11.1"
#    - run: sudo apt install xvfb
#    - run: pip install --upgrade pip
#    - run: pip install .[dev]
#    - run: xvfb-run pytest tests/

  run-tests-ubuntu-22_04-python-3_11_2:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.11.2
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.2"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest tests/

  run-tests-ubuntu-22_04-python-3_11:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.11
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest tests/

#  run-tests-ubuntu-22_04-python-3_12_0_alpha5:
#    runs-on: ubuntu-22.04
#    name: Ubuntu 22.04, Python 3.12.0alpha5
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v4
#      with:
#        python-version: "3.12.0-alpha.5"
#    - run: sudo apt install xvfb
#    - run: pip install --upgrade pip
#    - run: pip install .[dev]
#    - run: xvfb-run pytest tests/

  run-tests-ubuntu-22_04-python-3_11_from_apt:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python from Apt
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install python3.11-full python3-pip xvfb
    - run: python3.11 -m pip install --upgrade pip
    - run: python3.11 -m pip install -e .[dev]
    - run: xvfb-run python3.11 -mpytest tests/

      #  run-tests-ubuntu-22_10-python-3_11_from_apt:
      #runs-on: ubuntu-22.10
      #name: Ubuntu 22.10, Python from Apt
      #steps:
      #- uses: actions/checkout@v3
      #- run: sudo apt install python3.11-full python3-pip xvfb
      #- run: python3.11 -m pip install --upgrade pip
      #- run: python3.11 -m pip install -e .[dev]
      #- run: xvfb-run python3.11 -mpytest tests/

      #run-tests-ubuntu-23_04-python-3_11_from_apt:
      #runs-on: ubuntu-23.04
      #name: Ubuntu 23.04, Python from Apt
      #steps:
      #- uses: actions/checkout@v3
      #- run: sudo apt install python3.11-full python3-pip xvfb
      #- run: python3.11 -m pip install --upgrade pip
      #- run: python3.11 -m pip install -e .[dev]
      #- run: xvfb-run python3.11 -mpytest tests/

#  run-tests-ubuntu-22_04-pypy3:
#    runs-on: ubuntu-22.04
#    name: Ubuntu 22.04, PyPy 3
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v4
#      with:
#        python-version: "pypy3.9"
#    - run: sudo apt install pypy3 pypy3-tk pypy3-dev xvfb
#    - run: pypy3 -mpip install -U pip wheel
#    - run: pypy3 -mpip install .[dev]
#    - run: xvfb-run pytest tests/
