name: Run Tests (On Push)
on:
  push:

jobs:
  run-tests-ubuntu-python-3_11:
    name: Ubuntu / Python 3.11
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest tests/

  run-tests-windows-python-3_11
    name: Windows / Python 3.11
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/

  run-tests-macos-13-python-3_11
    name: MacOS 13 / Python 3.11
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/
