name: Run Tests (On Push)
on:
  push:

jobs:
  run-tests-ubuntu-22_04-python-3_11:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.11
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
    - run: sudo apt install xvfb fonts-ubuntu fonts-opensymbol xfonts-utils xfonts-encodings xfonts-base tcl-ttkthemes
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run strace -o test_font.strace python test_font.py
    - run: echo '### STRACE' >> $GITHUB_STEP_SUMMARY
    - run: cat test_font.strace >> $GITHUB_STEP_SUMMARY
