name: Run Tests (non-Linux)
on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  run-tests-windows-2019:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-2019
    name: Windows Server 2019
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/

  run-tests-windows-2022:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-2022
    name: Windows Server 2022
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/

  run-tests-macos-11:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-11
    name: macOS 11
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/

  run-tests-macos-12:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-12
    name: macOS 12
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/
