name: Run Tests (On Push)
on:
  push:

jobs:
  run-tests-ubuntu-22_04-python-3_9:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.9
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.9"
        cache: 'pip'
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest -v -rP --doctest-modules countess/ tests/

  run-tests-ubuntu-22_04-python-3_10:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest -v -rP --doctest-modules countess/ tests/

  run-tests-ubuntu-22_04-python-3_11_from_apt:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.11 from Apt
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt install python3.11-full python3-pip xvfb
    - run: python3.11 -m pip install --upgrade pip
    - run: python3.11 -m pip install -e .[dev]
    - run: xvfb-run python3.11 -m pytest -v -rP --doctest-modules countess/ tests/

#  run-tests-ubuntu-24_04-python-3_12_from_apt:
#    runs-on: ubuntu-24.04
#    name: Ubuntu 24.04, Python 3.12 from Apt
#    steps:
#    - uses: actions/checkout@v4
#    - run: sudo apt install python3.12-full python3-pip xvfb
#    - run: python3.12 -m venv /tmp/venv
#    - run: /tmp/venv/bin/python -m pip install --upgrade pip
#    - run: /tmp/venv/bin/python -m pip install -e .[dev]
#    - run: xvfb-run /tmp/venv/bin/python -m pytest -v -rP --doctest-modules countess/ tests/

  run-tests-ubuntu-24_04-python-3_x:
    runs-on: ubuntu-24.04
    name: Ubuntu 24.04, Python 3.x
    steps:
    - run: sudo apt-get -U upgrade -y
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: 'pip'
    - run: sudo apt install xvfb
    - run: python3 -m venv /tmp/venv
    - run: /tmp/venv/bin/python -m pip install --upgrade pip
    - run: /tmp/venv/bin/python -m pip install -e .[dev]
    - run: xvfb-run /tmp/venv/bin/coverage run --source countess -m pytest -v -rP --doctest-modules countess/ tests/
    - run: echo '### Coverage Report' >> $GITHUB_STEP_SUMMARY
    - run: /tmp/venv/bin/coverage report --format=markdown --skip-empty --sort=-cover >> $GITHUB_STEP_SUMMARY
