name: Run Tests (On Push)
on:
  push:

jobs:
  testing-123:
    runs-on: ubuntu-22.04
    name: name
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: "pip"
    - run: sudo apt install xvfb fonts-ubuntu fonts-opensymbol xfonts-utils xfonts-encodings xfonts-base tcl-ttkthemes
    - run: pip install --upgrade pip
    - run: pip install ttkthemes
    - run: xvfb-run strace -o test_font.strace python countess/gui/widgets.py || true
    - run: echo '### STRACE' >> $GITHUB_STEP_SUMMARY
    - run: cat test_font.strace >> $GITHUB_STEP_SUMMARY
