name: Run Tests (PR)
on:
  pull_request:

jobs:
  run-tests-ubuntu-22_04-python-3_10:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python 3.10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest tests/
    - run: tests/cmd_tests.sh

  run-tests-ubuntu-22_04-python-3_11_from_apt:
    runs-on: ubuntu-22.04
    name: Ubuntu 22.04, Python from Apt
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt install python3.11-full python3-pip xvfb
    - run: python3.11 -m pip install --upgrade pip
    - run: python3.11 -m pip install -e .[dev]
    - run: xvfb-run python3.11 -mpytest tests/
    - run: tests/cmd_tests.sh

  run-tests-windows-2019:
    runs-on: windows-2019
    name: Windows Server 2019
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/

  run-tests-windows-2022:
    runs-on: windows-2022
    name: Windows Server 2022
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/

  run-tests-macos-11:
    runs-on: macos-11
    name: macOS 11
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/

  run-tests-macos-12:
    runs-on: macos-12
    name: macOS 12
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/
