name: Run Tests
on:
  pull_request:
  push:

jobs:
  run-tests-ubuntu-22_04-python-3_10:
    runs-on: ubuntu-22.04
    name: Run Tests (Ubuntu 22.04, Python 3.10)
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest tests/

  run-tests-ubuntu-22_04-python-3_11:
    runs-on: ubuntu-22.04
    name: Run Tests (Ubuntu 22.04, Python 3.11)
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - run: sudo apt install xvfb
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: xvfb-run pytest tests/

#  run-tests-ubuntu-22_04-pypy3:
#    runs-on: ubuntu-22.04
#    name: Run Tests (Ubuntu 22.04, PyPy 3)
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-python@v4
#      with:
#        python-version: "pypy3.9"
#    - run: sudo apt install pypy3 pypy3-tk pypy3-dev xvfb
#    - run: pypy3 -mpip install -U pip wheel
#    - run: pypy3 -mpip install .[dev]
#    - run: xvfb-run pytest tests/

  run-tests-windows-2022:
    runs-on: windows-2022
    name: Run Tests (Windows Server 2022)
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/

  run-tests-macos-12:
    runs-on: macos-12
    name: Run Tests (macOS 12)
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - run: pip install --upgrade pip
    - run: pip install .[dev]
    - run: pytest tests/
